/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package O_Interface;

import Boaders_Interface.BHouse.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author User
 */

public class Add_Anex extends javax.swing.JInternalFrame {

    /**
     * Creates new form B_BH_Interface
     */
   String Nic;
    public Add_Anex(String BNICNO) {
        initComponents();
        this.ONICL.setText(BNICNO);
        JLabel Nic=ONICL;
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        connect();
        AutoID ();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    
    public final void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
           // java.util.logging.Logger.getLogger(ReTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public void AutoID ()
    {
        
        try {
            Statement s= con.createStatement();
            rs = s.executeQuery("select Max(AID) from anex");
            rs.next();
            rs.getString("Max(AID)");
            
            
            if(rs.getString("Max(AID)")==null)
            {
            
                AID.setText("AID001");
                
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(AID)").substring(3,rs.getString("Max(AID)").length()));
                id++;
                AID.setText("AID"+String.format("%03d", id));
                
                
            }
            
        } catch (SQLException ex) { 
            //java.util.logging.Logger.getLogger(ReTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    byte[] photo1 =null;
        byte[] photo2 =null;
        byte[] photo3 =null;
        byte[] photo4 =null;
        String filename =null;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_AnexInterface = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AAddress = new javax.swing.JTextField();
        ATitle = new javax.swing.JTextField();
        APrice = new javax.swing.JTextField();
        ABathRooms = new javax.swing.JTextField();
        BHImage1 = new javax.swing.JLabel();
        BHImage2 = new javax.swing.JLabel();
        BHImage3 = new javax.swing.JLabel();
        BHImage4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ONICL = new javax.swing.JLabel();
        OBHClear = new javax.swing.JButton();
        BHRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AID = new javax.swing.JLabel();
        ADescription = new javax.swing.JTextField();
        ABrowse4 = new javax.swing.JButton();
        ABrowse1 = new javax.swing.JButton();
        ABrowse2 = new javax.swing.JButton();
        ABrowse3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        AAmenities = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ABedRooms = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ALocation = new javax.swing.JComboBox<>();

        Add_AnexInterface.setBackground(new java.awt.Color(255, 255, 255));
        Add_AnexInterface.setPreferredSize(new java.awt.Dimension(864, 440));

        jScrollPane1.setBackground(new java.awt.Color(29, 119, 209));

        jPanel2.setBackground(new java.awt.Color(29, 119, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(601, 950));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Title");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BathRooms");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price_Range");

        AAddress.setBackground(new java.awt.Color(29, 119, 209));
        AAddress.setForeground(new java.awt.Color(255, 255, 255));
        AAddress.setToolTipText("Street,house number,and /post co");
        AAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        AAddress.setPreferredSize(new java.awt.Dimension(35, 348));
        AAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AAddressActionPerformed(evt);
            }
        });

        ATitle.setBackground(new java.awt.Color(29, 119, 209));
        ATitle.setForeground(new java.awt.Color(255, 255, 255));
        ATitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        ATitle.setPreferredSize(new java.awt.Dimension(35, 348));
        ATitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATitleActionPerformed(evt);
            }
        });

        APrice.setBackground(new java.awt.Color(29, 119, 209));
        APrice.setForeground(new java.awt.Color(255, 255, 255));
        APrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        APrice.setPreferredSize(new java.awt.Dimension(35, 348));

        ABathRooms.setBackground(new java.awt.Color(29, 119, 209));
        ABathRooms.setForeground(new java.awt.Color(255, 255, 255));
        ABathRooms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        BHImage1.setForeground(new java.awt.Color(255, 255, 255));
        BHImage1.setText("image1");

        BHImage2.setForeground(new java.awt.Color(255, 255, 255));
        BHImage2.setText("image2");

        BHImage3.setForeground(new java.awt.Color(255, 255, 255));
        BHImage3.setText("image3");

        BHImage4.setForeground(new java.awt.Color(255, 255, 255));
        BHImage4.setText("image4");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIC");

        ONICL.setForeground(new java.awt.Color(255, 255, 255));
        ONICL.setText("200025501935");
        ONICL.setPreferredSize(new java.awt.Dimension(35, 348));

        OBHClear.setText("Clear");
        OBHClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBHClearActionPerformed(evt);
            }
        });

        BHRegister.setText("Register");
        BHRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHRegisterActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AID");

        AID.setForeground(new java.awt.Color(255, 255, 255));
        AID.setPreferredSize(new java.awt.Dimension(35, 348));

        ADescription.setBackground(new java.awt.Color(29, 119, 209));
        ADescription.setForeground(new java.awt.Color(255, 255, 255));
        ADescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ADescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADescriptionActionPerformed(evt);
            }
        });

        ABrowse4.setText("Browse");
        ABrowse4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABrowse4ActionPerformed(evt);
            }
        });

        ABrowse1.setText("Browse");
        ABrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABrowse1ActionPerformed(evt);
            }
        });

        ABrowse2.setText("Browse");
        ABrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABrowse2ActionPerformed(evt);
            }
        });

        ABrowse3.setText("Browse");
        ABrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABrowse3ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Amenities");

        AAmenities.setBackground(new java.awt.Color(29, 119, 209));
        AAmenities.setForeground(new java.awt.Color(255, 255, 255));
        AAmenities.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        AAmenities.setPreferredSize(new java.awt.Dimension(35, 348));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BedRooms");

        ABedRooms.setBackground(new java.awt.Color(29, 119, 209));
        ABedRooms.setForeground(new java.awt.Color(255, 255, 255));
        ABedRooms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        ABedRooms.setPreferredSize(new java.awt.Dimension(35, 348));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Description");

        ALocation.setBackground(new java.awt.Color(29, 119, 209));
        ALocation.setForeground(new java.awt.Color(255, 255, 255));
        ALocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Districts", "Colombo", "Gampaha", "Kalutara", "Kandy", "Matale", "Nuwara Eliya", "Galle", "Matara", "Hambantota", "Jaffna", "Kilinochchi", "Mannar", "Vavuniya", "Mullaitivu", "Batticaloa", "Ampara", "Trincomalee", "Kurunegala", "Puttalam", "Anuradhapura", "Polonnaruwa", "Badulla", "Moneragala ", "Ratnapura", "Kegalle" }));
        ALocation.setToolTipText("select");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ALocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(AAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ATitle, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(AAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(APrice, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ADescription, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ABedRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ABathRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(ONICL, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(AID, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BHImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ABrowse4)
                            .addComponent(ABrowse2)
                            .addComponent(ABrowse3)
                            .addComponent(ABrowse1))
                        .addGap(108, 108, 108)))
                .addGap(202, 202, 202))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OBHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(BHRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ONICL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(AAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ATitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABedRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABathRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADescription, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABrowse4))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABrowse2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BHImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ABrowse3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BHImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ABrowse1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OBHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout Add_AnexInterfaceLayout = new javax.swing.GroupLayout(Add_AnexInterface);
        Add_AnexInterface.setLayout(Add_AnexInterfaceLayout);
        Add_AnexInterfaceLayout.setHorizontalGroup(
            Add_AnexInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        Add_AnexInterfaceLayout.setVerticalGroup(
            Add_AnexInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_AnexInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_AnexInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AAddressActionPerformed

    private void ATitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATitleActionPerformed

    private void OBHClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBHClearActionPerformed
        // TODO add your handling code here:
        ALocation.setSelectedItem("");
        AAddress.setText("");
        ATitle.setText("");
        APrice.setText("");
        ABathRooms.setText("");
        BHImage1.setText("");
        BHImage2.setText("");
        BHImage3.setText("");
        BHImage4.setText("");

    }//GEN-LAST:event_OBHClearActionPerformed

    private void BHRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHRegisterActionPerformed
        // TODO add your handling code here:
        String BHID = AID.getText();
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            String s = "Insert into anex values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, BHID);
            ps.setString(2, ALocation.getSelectedItem().toString());
            ps.setString(3, AAddress.getText());
            ps.setString(4, ATitle.getText());
            ps.setString(5, APrice.getText());
            ps.setString(6, AAmenities.getText());
            ps.setString(7, ABedRooms.getText());
            ps.setString(8, ABathRooms.getText());
            ps.setString(9, ONICL.getText());
            ps.setString(10, ADescription.getText());
            ps.setBytes(11,photo1 );
            ps.setBytes(12,photo2 );
            ps.setBytes(13,photo3 );
            ps.setBytes(14,photo4 );
            //ps.setString(15, ADescription.getText());

            int rs1 = ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Anex Register Succesfully");
            
            Add_Anex anex =new Add_Anex(Nic);
            Add_AnexInterface.removeAll();
            Add_AnexInterface.add(anex).setVisible(true);        
         
            ps.close();
            con.close();

        }

        catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Boarding House Register UNSuccesfully","Message",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BHRegisterActionPerformed

    private void ABrowse4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABrowse4ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);

        int showOpenDialog = browseImagefile.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION){
            File selectedImageFile =browseImagefile.getSelectedFile();
            String selectImagePath =selectedImageFile.getAbsolutePath();
            JOptionPane.showConfirmDialog(null, selectImagePath) ;

            //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
            filename=selectedImageFile.getAbsolutePath();
            BHImage1.setText(filename);

            try {
                File image =new File (filename);
                FileInputStream fis =new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte [] buf =new byte [488888];
                for (int readNum; (readNum =fis.read(buf))!= -1;){
                    bos.write(buf,0,readNum);
                }

                photo4 =bos.toByteArray();

            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e );
            }
            //  return null;
        }

    }//GEN-LAST:event_ABrowse4ActionPerformed

    private void ABrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABrowse1ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage4.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo1 =bos.toByteArray();
           
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_ABrowse1ActionPerformed

    private void ABrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABrowse2ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage2.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo2 =bos.toByteArray();
           
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_ABrowse2ActionPerformed

    private void ABrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABrowse3ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage3.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo3 =bos.toByteArray();
           
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_ABrowse3ActionPerformed

    private void ADescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AAddress;
    private javax.swing.JTextField AAmenities;
    private javax.swing.JTextField ABathRooms;
    private javax.swing.JTextField ABedRooms;
    private javax.swing.JButton ABrowse1;
    private javax.swing.JButton ABrowse2;
    private javax.swing.JButton ABrowse3;
    private javax.swing.JButton ABrowse4;
    private javax.swing.JTextField ADescription;
    private javax.swing.JLabel AID;
    private javax.swing.JComboBox<String> ALocation;
    private javax.swing.JTextField APrice;
    private javax.swing.JTextField ATitle;
    private javax.swing.JPanel Add_AnexInterface;
    private javax.swing.JLabel BHImage1;
    private javax.swing.JLabel BHImage2;
    private javax.swing.JLabel BHImage3;
    private javax.swing.JLabel BHImage4;
    private javax.swing.JButton BHRegister;
    private javax.swing.JButton OBHClear;
    private javax.swing.JLabel ONICL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
