/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package O_Interface;

import Boaders_Interface.BHouse.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author User
 */

public class Add_BH extends javax.swing.JInternalFrame {

    /**
     * Creates new form B_BH_Interface
     */
    String Nic;
    public Add_BH(String BNICNO) {
        initComponents();
        this.ONICL.setText(BNICNO);
        JLabel Nic=ONICL;
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        connect();
        AutoID ();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    
    public final void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
           // java.util.logging.Logger.getLogger(ReTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public void AutoID ()
    {
        
        try {
            Statement s= con.createStatement();
            rs = s.executeQuery("select Max(BID) from boardinghouse");
            rs.next();
            rs.getString("Max(BID)");
            
            
            if(rs.getString("Max(BID)")==null)
            {
            
                BHI.setText("BHI001");
                
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(BID)").substring(3,rs.getString("Max(BID)").length()));
                id++;
                BHI.setText("BHI"+String.format("%03d", id));
                
                
            }
            
        } catch (SQLException ex) { 
            //java.util.logging.Logger.getLogger(ReTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    byte[] photo1 =null;
        byte[] photo2 =null;
        byte[] photo3 =null;
        byte[] photo4 =null;
        String filename =null;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_BHInterface = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BHAddress = new javax.swing.JTextField();
        BHTitle = new javax.swing.JTextField();
        BHPrice = new javax.swing.JTextField();
        BHAmenities = new javax.swing.JTextField();
        BHImage1 = new javax.swing.JLabel();
        BHImage2 = new javax.swing.JLabel();
        BHImage3 = new javax.swing.JLabel();
        BHImage4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ONICL = new javax.swing.JLabel();
        OBHClear = new javax.swing.JButton();
        BHRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BHI = new javax.swing.JLabel();
        RBrowse4 = new javax.swing.JButton();
        RBrowse1 = new javax.swing.JButton();
        RBrowse2 = new javax.swing.JButton();
        RBrowse3 = new javax.swing.JButton();
        ALocation = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        BedRooms = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BathRoom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descrioption = new javax.swing.JTextArea();

        Add_BHInterface.setBackground(new java.awt.Color(255, 255, 255));
        Add_BHInterface.setPreferredSize(new java.awt.Dimension(864, 440));

        jScrollPane1.setBackground(new java.awt.Color(29, 119, 209));

        jPanel2.setBackground(new java.awt.Color(29, 119, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Title");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amenities");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price_Range");

        BHAddress.setBackground(new java.awt.Color(29, 119, 209));
        BHAddress.setForeground(new java.awt.Color(255, 255, 255));
        BHAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        BHAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHAddressActionPerformed(evt);
            }
        });

        BHTitle.setBackground(new java.awt.Color(29, 119, 209));
        BHTitle.setForeground(new java.awt.Color(255, 255, 255));
        BHTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        BHTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHTitleActionPerformed(evt);
            }
        });

        BHPrice.setBackground(new java.awt.Color(29, 119, 209));
        BHPrice.setForeground(new java.awt.Color(255, 255, 255));
        BHPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        BHAmenities.setBackground(new java.awt.Color(29, 119, 209));
        BHAmenities.setForeground(new java.awt.Color(255, 255, 255));
        BHAmenities.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        BHImage1.setForeground(new java.awt.Color(255, 255, 255));
        BHImage1.setText("image1");
        BHImage1.setPreferredSize(new java.awt.Dimension(120, 20));

        BHImage2.setForeground(new java.awt.Color(255, 255, 255));
        BHImage2.setText("image2");
        BHImage2.setPreferredSize(new java.awt.Dimension(120, 20));

        BHImage3.setForeground(new java.awt.Color(255, 255, 255));
        BHImage3.setText("image3");
        BHImage3.setPreferredSize(new java.awt.Dimension(120, 20));

        BHImage4.setForeground(new java.awt.Color(255, 255, 255));
        BHImage4.setText("image4");
        BHImage4.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIC");

        ONICL.setForeground(new java.awt.Color(255, 255, 255));
        ONICL.setText("200025501931");

        OBHClear.setText("Clear");
        OBHClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBHClearActionPerformed(evt);
            }
        });

        BHRegister.setText("Register");
        BHRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHRegisterActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BID");

        BHI.setForeground(new java.awt.Color(255, 255, 255));

        RBrowse4.setText("Browse");
        RBrowse4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse4ActionPerformed(evt);
            }
        });

        RBrowse1.setText("Browse");
        RBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse1ActionPerformed(evt);
            }
        });

        RBrowse2.setText("Browse");
        RBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse2ActionPerformed(evt);
            }
        });

        RBrowse3.setText("Browse");
        RBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse3ActionPerformed(evt);
            }
        });

        ALocation.setBackground(new java.awt.Color(29, 119, 209));
        ALocation.setForeground(new java.awt.Color(255, 255, 255));
        ALocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Districts", "Colombo", "Gampaha", "Kalutara", "Kandy", "Matale", "Nuwara Eliya", "Galle", "Matara", "Hambantota", "Jaffna", "Kilinochchi", "Mannar", "Vavuniya", "Mullaitivu", "Batticaloa", "Ampara", "Trincomalee", "Kurunegala", "Puttalam", "Anuradhapura", "Polonnaruwa", "Badulla", "Moneragala ", "Ratnapura", "Kegalle" }));
        ALocation.setToolTipText("Select Districts");
        ALocation.setBorder(null);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BedRooms");

        BedRooms.setBackground(new java.awt.Color(29, 119, 209));
        BedRooms.setForeground(new java.awt.Color(255, 255, 255));
        BedRooms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BathRooms");

        BathRoom.setBackground(new java.awt.Color(29, 119, 209));
        BathRoom.setForeground(new java.awt.Color(255, 255, 255));
        BathRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        BathRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BathRoomActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descrioption");

        Descrioption.setBackground(new java.awt.Color(29, 119, 209));
        Descrioption.setColumns(20);
        Descrioption.setForeground(new java.awt.Color(255, 255, 255));
        Descrioption.setRows(5);
        Descrioption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(Descrioption);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RBrowse2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BedRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BathRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(BHImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBrowse1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ALocation, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BHImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBrowse4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BHImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(337, 337, 337)
                            .addComponent(RBrowse3))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)
                            .addComponent(ONICL, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)
                            .addComponent(BHI, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BHAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BHPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BHAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(OBHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(BHRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(BHImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ONICL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BHAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BedRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BathRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBrowse1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBrowse2)
                    .addComponent(BHImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBrowse3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBrowse4)
                    .addComponent(BHImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OBHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout Add_BHInterfaceLayout = new javax.swing.GroupLayout(Add_BHInterface);
        Add_BHInterface.setLayout(Add_BHInterfaceLayout);
        Add_BHInterfaceLayout.setHorizontalGroup(
            Add_BHInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        Add_BHInterfaceLayout.setVerticalGroup(
            Add_BHInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_BHInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add_BHInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BHAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHAddressActionPerformed

    private void BHTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHTitleActionPerformed

    private void OBHClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBHClearActionPerformed
        // TODO add your handling code here:
        ALocation.setSelectedItem("");
        BHAddress.setText("");
        BHTitle.setText("");
        BHPrice.setText("");
        BHAmenities.setText("");
        BHImage1.setText("");
        BHImage2.setText("");
        BHImage3.setText("");
        BHImage4.setText("");

    }//GEN-LAST:event_OBHClearActionPerformed

    private void BHRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHRegisterActionPerformed
        // TODO add your handling code here:
        String BHID = BHI.getText();
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            String s = "Insert into boardinghouse values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, BHID);
            ps.setString(2, ALocation.getSelectedItem().toString());
            ps.setString(3, BHAddress.getText());
            ps.setString(4, BHTitle.getText());
            ps.setString(5, BHPrice.getText());
            ps.setString(6, BHAmenities.getText());
            ps.setString(7, BedRooms.getText());
            ps.setString(8, BathRoom.getText());
            ps.setString(9, ONICL.getText());
            ps.setString(10, Descrioption.getText());
            ps.setBytes(11,photo1 );
            ps.setBytes(12,photo2 );
            ps.setBytes(13,photo3 );
            ps.setBytes(14,photo4 );

            int rs1 = ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Boarding House Register Succesfully");
            
            Add_BH bh =new Add_BH(Nic);
            Add_BHInterface.removeAll();
            Add_BHInterface.add(bh).setVisible(true); 

            ps.close();
            con.close();

        }

        catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Boarding House Register UNSuccesfully","Message",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BHRegisterActionPerformed

    private void RBrowse4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse4ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);

        int showOpenDialog = browseImagefile.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION){
            File selectedImageFile =browseImagefile.getSelectedFile();
            String selectImagePath =selectedImageFile.getAbsolutePath();
            JOptionPane.showConfirmDialog(null, selectImagePath) ;

            //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
            filename=selectedImageFile.getAbsolutePath();
            BHImage4.setText(filename);

            try {
                File image =new File (filename);
                FileInputStream fis =new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte [] buf =new byte [488888];
                for (int readNum; (readNum =fis.read(buf))!= -1;){
                    bos.write(buf,0,readNum);
                }

                photo1 =bos.toByteArray();

            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e );
            }
            //  return null;
        }

    }//GEN-LAST:event_RBrowse4ActionPerformed

    private void RBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse1ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage1.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo4 =bos.toByteArray();
           
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_RBrowse1ActionPerformed

    private void RBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse2ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage2.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo2 =bos.toByteArray();
           
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_RBrowse2ActionPerformed

    private void RBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse3ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage3.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo3 =bos.toByteArray();
           
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_RBrowse3ActionPerformed

    private void BathRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BathRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BathRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ALocation;
    private javax.swing.JPanel Add_BHInterface;
    private javax.swing.JTextField BHAddress;
    private javax.swing.JTextField BHAmenities;
    private javax.swing.JLabel BHI;
    private javax.swing.JLabel BHImage1;
    private javax.swing.JLabel BHImage2;
    private javax.swing.JLabel BHImage3;
    private javax.swing.JLabel BHImage4;
    private javax.swing.JTextField BHPrice;
    private javax.swing.JButton BHRegister;
    private javax.swing.JTextField BHTitle;
    private javax.swing.JTextField BathRoom;
    private javax.swing.JTextField BedRooms;
    private javax.swing.JTextArea Descrioption;
    private javax.swing.JButton OBHClear;
    private javax.swing.JLabel ONICL;
    private javax.swing.JButton RBrowse1;
    private javax.swing.JButton RBrowse2;
    private javax.swing.JButton RBrowse3;
    private javax.swing.JButton RBrowse4;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
