/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package O_Interface;

import Boaders_Interface.*;
import Register.*;
import Home.BH_Home;
import Home.B_Body;
import Home.Body;
import Login.LoginHome;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */

public class O_Interface extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register_Home
     */
    Color DefaultColor,ClickedColor;
    String BNICNO;
    
    
    
    public O_Interface(String User,String Nic,String Lname, String Address, String Email, String PhoneNo) {
        initComponents();
        //Set coloer to BH,Anex
        DefaultColor =new Color (193, 208, 214);
        ClickedColor =new Color (45, 108, 133);
        //set Default color to pan on run time
        O_BH.setBackground(DefaultColor);
        O_Anex.setBackground(DefaultColor);
        
        
        BNICNO =new String(Nic);
        
        
        
        
        this.User.setText(User);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RE_Body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        O_BHLabel = new javax.swing.JPanel();
        O_BH = new javax.swing.JLabel();
        O_AnexLabel = new javax.swing.JPanel();
        O_Anex = new javax.swing.JLabel();
        LBack = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        OwnerIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BHLable = new javax.swing.JPanel();
        BH = new javax.swing.JLabel();
        AnexLable = new javax.swing.JPanel();
        Anex = new javax.swing.JLabel();
        OwnerInterfaceHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        RE_Body.setPreferredSize(new java.awt.Dimension(1024, 440));

        jPanel1.setBackground(new java.awt.Color(199, 225, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        O_BHLabel.setBackground(new java.awt.Color(193, 208, 214));

        O_BH.setBackground(new java.awt.Color(193, 208, 214));
        O_BH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        O_BH.setForeground(new java.awt.Color(255, 255, 255));
        O_BH.setText("Boarding House");
        O_BH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        O_BH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                O_BHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                O_BHMousePressed(evt);
            }
        });

        javax.swing.GroupLayout O_BHLabelLayout = new javax.swing.GroupLayout(O_BHLabel);
        O_BHLabel.setLayout(O_BHLabelLayout);
        O_BHLabelLayout.setHorizontalGroup(
            O_BHLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(O_BHLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(O_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        O_BHLabelLayout.setVerticalGroup(
            O_BHLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, O_BHLabelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(O_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(O_BHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        O_AnexLabel.setBackground(new java.awt.Color(193, 208, 214));

        O_Anex.setBackground(new java.awt.Color(193, 208, 214));
        O_Anex.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        O_Anex.setForeground(new java.awt.Color(255, 255, 255));
        O_Anex.setText("          Annex");
        O_Anex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        O_Anex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                O_AnexMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                O_AnexMousePressed(evt);
            }
        });

        javax.swing.GroupLayout O_AnexLabelLayout = new javax.swing.GroupLayout(O_AnexLabel);
        O_AnexLabel.setLayout(O_AnexLabelLayout);
        O_AnexLabelLayout.setHorizontalGroup(
            O_AnexLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(O_AnexLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(O_AnexLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(O_Anex, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        O_AnexLabelLayout.setVerticalGroup(
            O_AnexLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(O_AnexLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(O_AnexLabelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(O_Anex, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(O_AnexLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 40));

        LBack.setText("Log out");
        LBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBackMouseClicked(evt);
            }
        });
        LBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBackActionPerformed(evt);
            }
        });
        jPanel1.add(LBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 30));

        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("Name....");
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, 20));

        OwnerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        OwnerIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OwnerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OwnerIconMouseClicked(evt);
            }
        });
        jPanel1.add(OwnerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Add");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 30, -1));

        jLabel3.setText("00000");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        BHLable.setBackground(new java.awt.Color(193, 208, 214));

        BH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BH.setForeground(new java.awt.Color(255, 255, 255));
        BH.setText("Boarding House");
        BH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BHMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BHLableLayout = new javax.swing.GroupLayout(BHLable);
        BHLable.setLayout(BHLableLayout);
        BHLableLayout.setHorizontalGroup(
            BHLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BHLableLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(BH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BHLableLayout.setVerticalGroup(
            BHLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BHLableLayout.createSequentialGroup()
                .addComponent(BH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(BHLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        AnexLable.setBackground(new java.awt.Color(193, 208, 214));

        Anex.setBackground(new java.awt.Color(205, 211, 248));
        Anex.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Anex.setForeground(new java.awt.Color(255, 255, 255));
        Anex.setText("         Anex");
        Anex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Anex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnexMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AnexMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AnexLableLayout = new javax.swing.GroupLayout(AnexLable);
        AnexLable.setLayout(AnexLableLayout);
        AnexLableLayout.setHorizontalGroup(
            AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnexLableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Anex, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        AnexLableLayout.setVerticalGroup(
            AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnexLableLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(Anex)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        jPanel1.add(AnexLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        OwnerInterfaceHome.setBackground(new java.awt.Color(29, 119, 209));
        OwnerInterfaceHome.setPreferredSize(new java.awt.Dimension(864, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/D_ICON/22.png"))); // NOI18N

        javax.swing.GroupLayout OwnerInterfaceHomeLayout = new javax.swing.GroupLayout(OwnerInterfaceHome);
        OwnerInterfaceHome.setLayout(OwnerInterfaceHomeLayout);
        OwnerInterfaceHomeLayout.setHorizontalGroup(
            OwnerInterfaceHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OwnerInterfaceHomeLayout.setVerticalGroup(
            OwnerInterfaceHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RE_BodyLayout = new javax.swing.GroupLayout(RE_Body);
        RE_Body.setLayout(RE_BodyLayout);
        RE_BodyLayout.setHorizontalGroup(
            RE_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RE_BodyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(OwnerInterfaceHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RE_BodyLayout.setVerticalGroup(
            RE_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(OwnerInterfaceHome, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RE_Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RE_Body, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LBackActionPerformed

    private void O_BHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O_BHMouseClicked
        // TODO add your handling code here:
        
        Add_BH AddBH= new Add_BH(BNICNO);
        OwnerInterfaceHome.removeAll();
        OwnerInterfaceHome.add(AddBH).setVisible(true);
        
    }//GEN-LAST:event_O_BHMouseClicked

    private void O_AnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O_AnexMouseClicked
        // TODO add your handling code here:
        Add_Anex AddAnex= new Add_Anex(BNICNO);
        OwnerInterfaceHome.removeAll();
        OwnerInterfaceHome.add(AddAnex).setVisible(true);
        
    }//GEN-LAST:event_O_AnexMouseClicked

    private void LBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBackMouseClicked
        // TODO add your handling code here:
        B_Body body = new B_Body();
        RE_Body.removeAll();
        RE_Body.add(body).setVisible(true);
    }//GEN-LAST:event_LBackMouseClicked

    private void O_BHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O_BHMousePressed
        // TODO add your handling code here:
        O_BHLabel.setBackground(ClickedColor);
        O_AnexLabel.setBackground(DefaultColor);
    }//GEN-LAST:event_O_BHMousePressed

    private void O_AnexMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O_AnexMousePressed
        // TODO add your handling code here:
        O_BHLabel.setBackground(DefaultColor);
        O_AnexLabel.setBackground(ClickedColor);
    }//GEN-LAST:event_O_AnexMousePressed

    private void OwnerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerIconMouseClicked
        // TODO add your handling code here:
        String Nic1 =  BNICNO;
        try {
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", ""); 

        String st = "select * from owner where NIC=?";
        PreparedStatement pst = con.prepareStatement(st);
        pst.setString(1, Nic1);
        ResultSet rs = pst.executeQuery();
       
        if (rs.next()) {
            String Nic = rs.getString("NIC");
            String Fname = rs.getString("Fname");
            String Lname = rs.getString("Lname");
            String Address = rs.getString("Address");
            String Email = rs.getString("Email");
            String PhoneNo = rs.getString("Phone");
            
            
        OwnerDetails bodaerdetails = new OwnerDetails(Nic1, Fname, Lname, Address, Email, PhoneNo);
        OwnerInterfaceHome.removeAll();
        OwnerInterfaceHome.add(bodaerdetails).setVisible(true);

        
        }
         
         pst.executeQuery();
        //The close() method is used to close the stream and release 
        //the resources that were busy in the stream
        
        pst.close();
        con.close();
        
          
        }
            catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
        
        }
       
    }//GEN-LAST:event_OwnerIconMouseClicked

    private void BHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHMouseClicked
        // TODO add your handling code here:
        B_BH_Interface bh = new B_BH_Interface();
        OwnerInterfaceHome.removeAll();
        OwnerInterfaceHome.add(bh).setVisible(true);
    }//GEN-LAST:event_BHMouseClicked

    private void BHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHMousePressed
        // TODO add your handling code here:
        BHLable.setBackground(ClickedColor);
        AnexLable.setBackground(DefaultColor);
    }//GEN-LAST:event_BHMousePressed

    private void AnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnexMouseClicked
        // TODO add your handling code here:

        B_Anex_Interface bh = new B_Anex_Interface();
        OwnerInterfaceHome.removeAll();
        OwnerInterfaceHome.add(bh).setVisible(true);
    }//GEN-LAST:event_AnexMouseClicked

    private void AnexMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnexMousePressed
        // TODO add your handling code here:
        BHLable.setBackground(DefaultColor);
        AnexLable.setBackground(ClickedColor);
    }//GEN-LAST:event_AnexMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anex;
    private javax.swing.JPanel AnexLable;
    private javax.swing.JLabel BH;
    private javax.swing.JPanel BHLable;
    private javax.swing.JButton LBack;
    private javax.swing.JLabel O_Anex;
    private javax.swing.JPanel O_AnexLabel;
    private javax.swing.JLabel O_BH;
    private javax.swing.JPanel O_BHLabel;
    private javax.swing.JLabel OwnerIcon;
    private javax.swing.JPanel OwnerInterfaceHome;
    private javax.swing.JPanel RE_Body;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
