/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package O_Interface;

import Boaders_Interface.*;
import Home.BH_Home;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class OwnerDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form BoaderDetails
     */
    String BNICNO;
    String BDFname;
    String BDLname;
    String BDAddress;
    String BDEmail;
    String BDPhoneNo;
    
    
    public OwnerDetails(String nic, String Fname, String Lname, String Address, String Email, String PhoneNo) {
        initComponents();
        //////B_Interface////////
        this.BNIC.setText(nic);
        this.BFName.setText(Fname);
        this.BSName.setText(Lname);
        this.BAsdderss.setText(Address);
        this.BEmail.setText(Email);
        this.BPhone.setText(PhoneNo);
        
        
        ////ODetails//////
        BNICNO =new String(nic);
        BDFname =new String(Fname);
        BDLname =new String(Lname);
        BDAddress =new String(Address);
        BDEmail =new String(Email);
        BDPhoneNo =new String(PhoneNo);
       
        ////ODetails//////
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }
    
      
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BDetails = new javax.swing.JPanel();
        profilePIC = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Anex = new javax.swing.JButton();
        BoardingHouse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Adderss1 = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        NIC = new javax.swing.JLabel();
        Sname = new javax.swing.JLabel();
        BNIC = new javax.swing.JLabel();
        BFName = new javax.swing.JLabel();
        BSName = new javax.swing.JLabel();
        BAsdderss = new javax.swing.JLabel();
        BEmail = new javax.swing.JLabel();
        BPhone = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        BDetails.setBackground(new java.awt.Color(255, 255, 255));
        BDetails.setPreferredSize(new java.awt.Dimension(864, 440));

        profilePIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        profilePIC.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("My Adds"));

        Anex.setText("Anex");
        Anex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnexMouseClicked(evt);
            }
        });

        BoardingHouse.setText("BoardingHouse");
        BoardingHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoardingHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Anex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(BoardingHouse)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anex)
                    .addComponent(BoardingHouse))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));

        Phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phone.setText("Phone Number");

        Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Email.setText("Email");

        Adderss1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Adderss1.setText("Adderss");

        Fname.setBackground(new java.awt.Color(54, 161, 212));
        Fname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Fname.setText("Frist Name");

        NIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NIC.setText("NIC");

        Sname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Sname.setText("Second Name ");

        BNIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BNIC.setText("nic");
        BNIC.setPreferredSize(new java.awt.Dimension(250, 30));

        BFName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BFName.setText("fname");
        BFName.setPreferredSize(new java.awt.Dimension(250, 30));

        BSName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BSName.setText("jLabel3");
        BSName.setPreferredSize(new java.awt.Dimension(250, 30));

        BAsdderss.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BAsdderss.setText("jLabel3");
        BAsdderss.setPreferredSize(new java.awt.Dimension(250, 30));

        BEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BEmail.setText("jLabel3");
        BEmail.setPreferredSize(new java.awt.Dimension(250, 30));

        BPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BPhone.setText("jLabel3");
        BPhone.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Adderss1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(BAsdderss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BFName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BSName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Adderss1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BAsdderss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        jButton3.setText("Delect Account");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BDetailsLayout = new javax.swing.GroupLayout(BDetails);
        BDetails.setLayout(BDetailsLayout);
        BDetailsLayout.setHorizontalGroup(
            BDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profilePIC)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(329, 329, 329))
        );
        BDetailsLayout.setVerticalGroup(
            BDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDetailsLayout.createSequentialGroup()
                .addGroup(BDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BDetailsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(profilePIC))
                    .addGroup(BDetailsLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BDetailsLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update)
                            .addComponent(jButton3))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
        String Nic1 = BNICNO;
        String Fname=BDFname;
        String Lname=BDLname;
        String Address=BDAddress;
        String Email=BDEmail;
        String PhoneNo=BDPhoneNo;
        

        UpdateOwnerDetails bodaerdetails = new UpdateOwnerDetails(Nic1, Fname, Lname, Address, Email, PhoneNo);
        BDetails.removeAll();
        BDetails.add(bodaerdetails).setVisible(true);
    }//GEN-LAST:event_UpdateMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            String ID =BNIC.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            // executeUpdate(String SQL):
            String s = "delete from owner where NIC=?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, ID);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Youer Account is Delete auto logout");

            //        B_Body body = new B_Body();
            //        B_Interface.RE_Body.removeAll();
            //        B_Interface.RE_Body.add(body).setVisible(true);

            BH_Home reg1 =new BH_Home();
            reg1.show();
            this.dispose();
            reg1.setVisible(true);

            ps.close();
            con.close();

        }catch(HeadlessException | ClassNotFoundException | SQLException e){

            System.out.println(e);

        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void AnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnexMouseClicked
        // TODO add your handling code here:
        String Nic1 = BNICNO;
        O_Anex oanex = new O_Anex(Nic1);
        BDetails.removeAll();
        BDetails.add(oanex).setVisible(true);
    }//GEN-LAST:event_AnexMouseClicked

    private void BoardingHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoardingHouseActionPerformed
        // TODO add your handling code here:
        String Nic1 = BNICNO;
        O_BH oanex = new O_BH(Nic1);
        BDetails.removeAll();
        BDetails.add(oanex).setVisible(true);
    }//GEN-LAST:event_BoardingHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adderss1;
    private javax.swing.JButton Anex;
    private javax.swing.JLabel BAsdderss;
    private javax.swing.JPanel BDetails;
    private javax.swing.JLabel BEmail;
    private javax.swing.JLabel BFName;
    private javax.swing.JLabel BNIC;
    private javax.swing.JLabel BPhone;
    private javax.swing.JLabel BSName;
    private javax.swing.JButton BoardingHouse;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel NIC;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Sname;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel profilePIC;
    // End of variables declaration//GEN-END:variables
}
