/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package O_Interface;

import Boaders_Interface.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class UpdateOwnerDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form BoaderDetails
     */
    
    public UpdateOwnerDetails(String nic, String Fname, String Lname, String Address, String Email, String PhoneNo) {
        initComponents();
        //////B_Interface////////
        this.BNIC.setText(nic);
        this.BFName.setText(Fname);
        this.BSName.setText(Lname);
        this.BAsdderss.setText(Address);
        this.BEmail.setText(Email);
        this.BPhone.setText(PhoneNo);
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }
    
      
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ODetails = new javax.swing.JPanel();
        profilePIC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Adderss1 = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        NIC = new javax.swing.JLabel();
        Sname = new javax.swing.JLabel();
        BNIC = new javax.swing.JLabel();
        BFName = new javax.swing.JTextField();
        BSName = new javax.swing.JTextField();
        BAsdderss = new javax.swing.JTextField();
        BEmail = new javax.swing.JTextField();
        BPhone = new javax.swing.JTextField();
        Save = new javax.swing.JButton();

        ODetails.setBackground(new java.awt.Color(255, 255, 255));
        ODetails.setPreferredSize(new java.awt.Dimension(864, 440));

        profilePIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        profilePIC.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));

        Phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phone.setText("Phone Number");

        Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Email.setText("Email");

        Adderss1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Adderss1.setText("Adderss");

        Fname.setBackground(new java.awt.Color(54, 161, 212));
        Fname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Fname.setText("Frist Name");

        NIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NIC.setText("NIC");

        Sname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Sname.setText("Second Name ");

        BNIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BNIC.setText("nic");
        BNIC.setPreferredSize(new java.awt.Dimension(250, 30));

        BFName.setText("jTextField1");

        BSName.setText("jTextField2");

        BAsdderss.setText("jTextField3");

        BEmail.setText("jTextField4");

        BPhone.setText("jTextField5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adderss1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAsdderss, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Adderss1, Email, Fname, NIC, Phone, Sname});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BFName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BAsdderss, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Adderss1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Adderss1, Email, Fname, NIC, Phone, Sname});

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ODetailsLayout = new javax.swing.GroupLayout(ODetails);
        ODetails.setLayout(ODetailsLayout);
        ODetailsLayout.setHorizontalGroup(
            ODetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ODetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ODetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Save)
                    .addGroup(ODetailsLayout.createSequentialGroup()
                        .addComponent(profilePIC)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(317, 317, 317))
        );
        ODetailsLayout.setVerticalGroup(
            ODetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ODetailsLayout.createSequentialGroup()
                .addGroup(ODetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ODetailsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(profilePIC))
                    .addGroup(ODetailsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Save)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ODetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ODetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String NICNO =BNIC.getText();
        String DFname = BFName.getText();
        String DLname = BSName.getText();
        String DAddress = BAsdderss.getText();
        String DEmail = BEmail.getText();
        String DPhoneNo = BPhone.getText();
        try {
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
        // executeUpdate(String SQL):
        String s = "update owner set Fname=?, Lname=?, Address=?, Email=?, Phone=? where NIC=?";
        PreparedStatement ps = con.prepareStatement(s);
        
        ps.setString(1, DFname);
        ps.setString(2, DLname);
        ps.setString(3, DAddress);
        ps.setString(4, DEmail);
        ps.setString(5, DPhoneNo);
        ps.setString(6, NICNO);
        ps.executeUpdate();
        //executeUpdate(String SQL)
        
        ////////Update deatails///////////////////////
       String ID =BNIC.getText();
        
        String st = "select * from owner where NIC=?";
        PreparedStatement pst = con.prepareStatement(st);
        pst.setString(1, ID);
        ResultSet rs = pst.executeQuery();
       
        if (rs.next()) {
            String Nic = rs.getString("NIC");
            String FName = rs.getString("Fname");
            String Lname = rs.getString("Lname");
            String Address = rs.getString("Address");
            String Email = rs.getString("Email");
            String PhoneNo = rs.getString("Phone");
            
            
            OwnerDetails bodaerdetails = new OwnerDetails(Nic, FName, Lname, Address, Email, PhoneNo);
            ODetails.removeAll();
            ODetails.add(bodaerdetails).setVisible(true);
        }
        //////////Update deatails////////////////////
       
        pst.executeQuery();
        //The close() method is used to close the stream and release 
        //the resources that were busy in the stream
        ps.close();
        pst.close();
        con.close();
        
          
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
        
            System.out.println(e);
        
        }
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adderss1;
    private javax.swing.JTextField BAsdderss;
    private javax.swing.JTextField BEmail;
    private javax.swing.JTextField BFName;
    private javax.swing.JLabel BNIC;
    private javax.swing.JTextField BPhone;
    private javax.swing.JTextField BSName;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel NIC;
    private javax.swing.JPanel ODetails;
    private javax.swing.JLabel Phone;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Sname;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel profilePIC;
    // End of variables declaration//GEN-END:variables
}
