/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Boaders_Interface;

import Boaders_Interface.Anex.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class B_Anex_Interface extends javax.swing.JInternalFrame {

    /**
     * Creates new form B_BH_Interface
     */
    public B_Anex_Interface() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bbody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        B_I_Body = new javax.swing.JPanel();
        BH2 = new javax.swing.JLabel();
        BH1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(876, 476));

        Bbody.setBackground(new java.awt.Color(255, 255, 255));
        Bbody.setPreferredSize(new java.awt.Dimension(864, 440));

        jScrollPane1.setBackground(new java.awt.Color(29, 119, 209));

        B_I_Body.setBackground(new java.awt.Color(255, 255, 255));
        B_I_Body.setMinimumSize(new java.awt.Dimension(870, 1500));
        B_I_Body.setPreferredSize(new java.awt.Dimension(879, 1500));
        B_I_Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/2.1.jpg"))); // NOI18N
        BH2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BH2MouseClicked(evt);
            }
        });
        B_I_Body.add(BH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 15, -1, 240));

        BH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/6.1.png"))); // NOI18N
        BH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BH1MouseClicked(evt);
            }
        });
        B_I_Body.add(BH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, 230));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/8.5.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        B_I_Body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 335, 400, 230));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/3.5.jpg"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        B_I_Body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, 390, 230));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Anex for Family");
        B_I_Body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Address :");
        B_I_Body.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Single story house");
        B_I_Body.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 980, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 180, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Address :");
        B_I_Body.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("14 Boarding Rooms");
        B_I_Body.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Address :");
        B_I_Body.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Anex for couple");
        B_I_Body.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("22/1,Kadawatha,Ragama ");
        B_I_Body.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Address :");
        B_I_Body.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/9.2.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        B_I_Body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 340, 300));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("4 Boarding Rooms");
        B_I_Body.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Thalgaswaththa Road, Hokandara North");
        B_I_Body.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1010, 260, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Address :");
        B_I_Body.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1010, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Single story house");
        B_I_Body.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 980, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Thalgaswaththa Road, Hokandara North");
        B_I_Body.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 1010, 260, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Address :");
        B_I_Body.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1010, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/6.6.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        B_I_Body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 370, 290));

        jScrollPane1.setViewportView(B_I_Body);
        B_I_Body.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout BbodyLayout = new javax.swing.GroupLayout(Bbody);
        Bbody.setLayout(BbodyLayout);
        BbodyLayout.setHorizontalGroup(
            BbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        BbodyLayout.setVerticalGroup(
            BbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BH1MouseClicked
        // TODO add your handling code here:
        B_Anex_1 body = new B_Anex_1();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_BH1MouseClicked

    private void BH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BH2MouseClicked
        // TODO add your handling code here:
        B_Anex_2 body = new B_Anex_2();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_BH2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        B_Anex_3 body = new B_Anex_3();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        B_Anex_4 body = new B_Anex_4();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        B_Anex_5 body = new B_Anex_5();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        B_Anex_6 body = new B_Anex_6();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BH1;
    private javax.swing.JLabel BH2;
    private javax.swing.JPanel B_I_Body;
    private javax.swing.JPanel Bbody;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
