/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Boaders_Interface;

import Boaders_Interface.BHouse.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class B_BH_Interface extends javax.swing.JInternalFrame {

    /**
     * Creates new form B_BH_Interface
     */
    public B_BH_Interface() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bbody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        B_I_Body = new javax.swing.JPanel();
        BH2 = new javax.swing.JLabel();
        BH1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(876, 476));

        Bbody.setBackground(new java.awt.Color(255, 255, 255));
        Bbody.setPreferredSize(new java.awt.Dimension(864, 440));

        jScrollPane1.setBackground(new java.awt.Color(29, 119, 209));

        B_I_Body.setBackground(new java.awt.Color(255, 255, 255));
        B_I_Body.setPreferredSize(new java.awt.Dimension(879, 775));
        B_I_Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/2.1.jpg"))); // NOI18N
        BH2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BH2MouseClicked(evt);
            }
        });
        B_I_Body.add(BH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 340, 240));

        BH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/1.3.jpg"))); // NOI18N
        BH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BH1MouseClicked(evt);
            }
        });
        B_I_Body.add(BH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/8.1.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        B_I_Body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 356, 400, 240));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boaders_Interface/Anex/Image/9.1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        B_I_Body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 360, 240));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("2 Boarding Rooms");
        B_I_Body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Address :");
        B_I_Body.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("4 Boarding Rooms");
        B_I_Body.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 180, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Address :");
        B_I_Body.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("14 Boarding Rooms");
        B_I_Body.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 615, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Address :");
        B_I_Body.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("5 Boarding Rooms");
        B_I_Body.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("23/1,makola, Kiribathgoda");
        B_I_Body.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 180, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Address :");
        B_I_Body.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("14 Boarding Rooms");
        B_I_Body.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 820, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 860, 180, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Address :");
        B_I_Body.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 860, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("14 Boarding Rooms");
        B_I_Body.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 820, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("233/1, Dalugama, Kelaniya");
        B_I_Body.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 860, 180, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Address :");
        B_I_Body.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 860, -1, -1));

        jScrollPane1.setViewportView(B_I_Body);

        javax.swing.GroupLayout BbodyLayout = new javax.swing.GroupLayout(Bbody);
        Bbody.setLayout(BbodyLayout);
        BbodyLayout.setHorizontalGroup(
            BbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        BbodyLayout.setVerticalGroup(
            BbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BH1MouseClicked
        // TODO add your handling code here:
       // B_BH_1 body = new B_BH_1(String Fname,String Lname,String Address,String Location,String Availbility,String Price_renge,String Amenities,String BedRooms,String BathRooms,String NIC,String Description);
        //Bbody.removeAll();
        //Bbody.add(body).setVisible(true);
        B_BH_1 body = new B_BH_1();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
                                    
    }//GEN-LAST:event_BH1MouseClicked

    private void BH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BH2MouseClicked
        // TODO add your handling code here:
        B_BH_2 body = new B_BH_2();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_BH2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        B_BH_3 body = new B_BH_3();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        B_BH_4 body = new B_BH_4();
        Bbody.removeAll();
        Bbody.add(body).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BH1;
    private javax.swing.JLabel BH2;
    private javax.swing.JPanel B_I_Body;
    private javax.swing.JPanel Bbody;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
