/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Boaders_Interface;

import Boaders_Interface.Anex.B_Anex;
import Boaders_Interface.BHouse.B_BH;

import Home.B_Body;
import java.awt.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class B_Interface extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register_Home
     */
    Color DefaultColor,ClickedColor;
    String BNICNO;
    String  FName;
    String LName;
    
    
    public B_Interface(String User,String Nic,String Lname, String Address, String Email, String PhoneNo, String WorkPlace) {
        initComponents();
         //Set coloer to BH,Anex
        DefaultColor =new Color (193, 208, 214);
        ClickedColor =new Color (45, 108, 133);
        //set Default color to pan on run time
        BHLable.setBackground(DefaultColor);
        AnexLable.setBackground(DefaultColor);
        
        
        BNICNO =new String(Nic);

        
        this.User.setText(User);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
      
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RE_Body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        BoaderIcon = new javax.swing.JLabel();
        BHLable = new javax.swing.JPanel();
        BH = new javax.swing.JLabel();
        AnexLable = new javax.swing.JPanel();
        Anex = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        Search1 = new javax.swing.JLabel();
        SeSearch = new javax.swing.JComboBox<>();
        BInterfaceHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        RE_Body.setPreferredSize(new java.awt.Dimension(1024, 440));

        jPanel1.setBackground(new java.awt.Color(199, 225, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 440));

        logout.setText("Log out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        User.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("Name....");

        BoaderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        BoaderIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoaderIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoaderIconMouseClicked(evt);
            }
        });

        BHLable.setBackground(new java.awt.Color(193, 208, 214));

        BH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BH.setForeground(new java.awt.Color(255, 255, 255));
        BH.setText("Boarding House");
        BH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BHMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BHLableLayout = new javax.swing.GroupLayout(BHLable);
        BHLable.setLayout(BHLableLayout);
        BHLableLayout.setHorizontalGroup(
            BHLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BHLableLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(BH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BHLableLayout.setVerticalGroup(
            BHLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BHLableLayout.createSequentialGroup()
                .addComponent(BH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        AnexLable.setBackground(new java.awt.Color(193, 208, 214));

        Anex.setBackground(new java.awt.Color(205, 211, 248));
        Anex.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Anex.setForeground(new java.awt.Color(255, 255, 255));
        Anex.setText("         Anex");
        Anex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Anex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnexMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AnexMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AnexLableLayout = new javax.swing.GroupLayout(AnexLable);
        AnexLable.setLayout(AnexLableLayout);
        AnexLableLayout.setHorizontalGroup(
            AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnexLableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Anex, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        AnexLableLayout.setVerticalGroup(
            AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(AnexLableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnexLableLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(Anex)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        Search.setToolTipText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Search1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search1.setForeground(new java.awt.Color(255, 255, 255));
        Search1.setText("search");
        Search1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search1MouseClicked(evt);
            }
        });

        SeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boarding House", "Anex" }));
        SeSearch.setSelectedIndex(1);
        SeSearch.setToolTipText("");
        SeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BoaderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BHLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AnexLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BoaderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BHLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(AnexLable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(SeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Search1)
                .addGap(70, 70, 70)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BInterfaceHome.setBackground(new java.awt.Color(29, 119, 209));
        BInterfaceHome.setPreferredSize(new java.awt.Dimension(864, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/D_ICON/choose b or a2.png"))); // NOI18N

        javax.swing.GroupLayout BInterfaceHomeLayout = new javax.swing.GroupLayout(BInterfaceHome);
        BInterfaceHome.setLayout(BInterfaceHomeLayout);
        BInterfaceHomeLayout.setHorizontalGroup(
            BInterfaceHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BInterfaceHomeLayout.setVerticalGroup(
            BInterfaceHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RE_BodyLayout = new javax.swing.GroupLayout(RE_Body);
        RE_Body.setLayout(RE_BodyLayout);
        RE_BodyLayout.setHorizontalGroup(
            RE_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RE_BodyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BInterfaceHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RE_BodyLayout.setVerticalGroup(
            RE_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BInterfaceHome, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RE_Body, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RE_Body, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_logoutActionPerformed

    private void BHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHMouseClicked
        // TODO add your handling code here:
        B_BH_Interface bh = new B_BH_Interface();
        BInterfaceHome.removeAll();
        BInterfaceHome.add(bh).setVisible(true);
    }//GEN-LAST:event_BHMouseClicked

    private void AnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnexMouseClicked
        // TODO add your handling code here:
        
        
        B_Anex_Interface bh = new B_Anex_Interface();
        BInterfaceHome.removeAll();
        BInterfaceHome.add(bh).setVisible(true);
    }//GEN-LAST:event_AnexMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        B_Body body = new B_Body();
        RE_Body.removeAll();
        RE_Body.add(body).setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void BHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHMousePressed
        // TODO add your handling code here:
        BHLable.setBackground(ClickedColor);
        AnexLable.setBackground(DefaultColor);
    }//GEN-LAST:event_BHMousePressed

    private void AnexMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnexMousePressed
        // TODO add your handling code here:
        BHLable.setBackground(DefaultColor);
        AnexLable.setBackground(ClickedColor);
    }//GEN-LAST:event_AnexMousePressed

    private void BoaderIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoaderIconMouseClicked
        // TODO add your handling code here:
        String Nic1 =  BNICNO;
        
       
        try {
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", ""); 
        
        
        String st = "select * from customer where NIC=?";
        PreparedStatement pst = con.prepareStatement(st);
        pst.setString(1, Nic1);
        ResultSet rs = pst.executeQuery();
       
        if (rs.next()) {
            String Nic = rs.getString("NIC");
            String Fname = rs.getString("Fname");
            String Lname = rs.getString("Lname");
            String Address = rs.getString("Address");
            String Email = rs.getString("Email");
            String PhoneNo = rs.getString("Phone");
            String WorkPlace = rs.getString("University_School_WorkPlace");
            

            
        
        BoaderDetails bodaerdetails = new BoaderDetails(Nic1, Fname, Lname, Address, Email, PhoneNo, WorkPlace);
        BInterfaceHome.removeAll();
        BInterfaceHome.add(bodaerdetails).setVisible(true);
        }
         
         pst.executeQuery();
        //The close() method is used to close the stream and release 
        //the resources that were busy in the stream
        
        pst.close();
        con.close();
        
          
        }
            catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
        
        }
    }//GEN-LAST:event_BoaderIconMouseClicked

    private void Search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search1MouseClicked
        // TODO add your handling code here:
        
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
        // executeUpdate(String SQL):
        
       //String address =Search.getText();
       String se=SeSearch.getSelectedItem().toString();
       if ("Anex".equals(se)){

        String st = "select * from anex where Location=?";
        PreparedStatement pst = con.prepareStatement(st);
        pst.setString(1, Search.getText());
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            String Address = rs.getString("Address");
            String Location = rs.getString("Location");
            String Title = rs.getString("Title");
            String Price_renge = rs.getString("Price_Range");
            String Amenities = rs.getString("Amenities");
            String BedRooms = rs.getString("BedRooms");
            String BathRooms = rs.getString("BathRooms");
            String NIC = rs.getString("NIC");
            String Description = rs.getString("Description");
            byte[] images1 =rs.getBytes("image1");
            byte[] images2 =rs.getBytes("image2");
            //String Ni =  BNICNO;
            
            String s = "select * from owner where NIC=?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, NIC);
            ResultSet rst = ps.executeQuery();
                
                if (rst.next()){
            String Fname = rst.getString("FName");
            String Lname = rst.getString("LName");
            String Email = rst.getString("Email");
            String Phone = rst.getString("Phone");
            B_Anex anex = new B_Anex(Fname,Lname,Address, Location, Title, Price_renge, Amenities, BedRooms, BathRooms, NIC,Email,Phone, Description,images1,images2);
            BInterfaceHome.removeAll();
            BInterfaceHome.add(anex).setVisible(true);
        }
                pst.close();
        }
        }
       else{
           String st = "select * from boardinghouse where Location=?";
        PreparedStatement pst = con.prepareStatement(st);
        pst.setString(1, Search.getText());
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            String Address = rs.getString("Address");
            String Location = rs.getString("Location");
            String Availbility = rs.getString("Title");
            String Price_renge = rs.getString("Price_Range");
            String Amenities = rs.getString("Amenities");
            String BedRooms = rs.getString("BedRooms");
            String BathRooms = rs.getString("BathRooms");
            String NIC = rs.getString("NIC");
            String Description = rs.getString("Description");
            byte[] images1 =rs.getBytes("BHImage4");
            byte[] images2 =rs.getBytes("BHImage2");
            //String Ni =  BNICNO;
            
            String s = "select * from owner where NIC=?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, NIC);
            ResultSet rst = ps.executeQuery();
                
                if (rst.next()){
            String Fname = rst.getString("FName");
            String Lname = rst.getString("LName");
            String Email = rst.getString("Email");
            String Phone = rst.getString("Phone");
                   
            B_BH anex = new B_BH(Fname,Lname,Address, Location, Availbility, Price_renge, Amenities,BedRooms, BathRooms, NIC,Email,Phone,Description,images1,images2);
            BInterfaceHome.removeAll();
            BInterfaceHome.add(anex).setVisible(true);
        }
                pst.close();
        }          
        
        }
        //pst.close();
        con.close();
        
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
        
            System.out.println(e);
        
        }
    }//GEN-LAST:event_Search1MouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anex;
    private javax.swing.JPanel AnexLable;
    private javax.swing.JLabel BH;
    private javax.swing.JPanel BHLable;
    private javax.swing.JPanel BInterfaceHome;
    private javax.swing.JLabel BoaderIcon;
    private javax.swing.JPanel RE_Body;
    private javax.swing.JComboBox<String> SeSearch;
    private javax.swing.JTextField Search;
    private javax.swing.JLabel Search1;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables

}
