/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to  change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Boaders_Interface;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class UpdateBoaderDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form BoaderDetails
     */
    
    
    public UpdateBoaderDetails(String nic, String Fname, String Lname, String Address, String Email, String PhoneNo, String WorkPlace) {
        initComponents();
        //////B_Interface////////
        this.BNIC.setText(nic);
        this.BFName.setText(Fname);
        this.BSName.setText(Lname);
        this.BAsdderss.setText(Address);
        this.BEmail.setText(Email);
        this.BPhone.setText(PhoneNo);
        this.BWorkPlace.setText(WorkPlace);
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }
    
      
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UBDetails = new javax.swing.JPanel();
        profilePIC = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NIC = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        Sname = new javax.swing.JLabel();
        Adderss1 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Phone1 = new javax.swing.JLabel();
        BNIC = new javax.swing.JLabel();
        BFName = new javax.swing.JTextField();
        BSName = new javax.swing.JTextField();
        BAsdderss = new javax.swing.JTextField();
        BEmail = new javax.swing.JTextField();
        BPhone = new javax.swing.JTextField();
        BWorkPlace = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();

        UBDetails.setBackground(new java.awt.Color(255, 255, 255));
        UBDetails.setPreferredSize(new java.awt.Dimension(864, 440));

        profilePIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        profilePIC.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(466, 338));

        NIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NIC.setText("NIC");

        Fname.setBackground(new java.awt.Color(54, 161, 212));
        Fname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Fname.setText("Frist Name");

        Sname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Sname.setText("Second Name ");

        Adderss1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Adderss1.setText("Adderss");

        Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Email.setText("Email");

        Phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phone.setText("Phone Number");

        Phone1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phone1.setText("University/School");

        BNIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BNIC.setText("nic");
        BNIC.setPreferredSize(new java.awt.Dimension(250, 30));

        BFName.setText("jTextField1");

        BSName.setText("jTextField2");

        BAsdderss.setText("jTextField3");

        BEmail.setText("jTextField4");

        BPhone.setText("jTextField5");
        BPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhoneActionPerformed(evt);
            }
        });

        BWorkPlace.setText("jTextField6");

        Label2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label2.setText("WorkPlace\t");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(Fname, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(Sname, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(Adderss1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(Phone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAsdderss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BWorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Adderss1, Email, Fname, NIC, Phone, Sname});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BAsdderss, BEmail, BFName, BPhone, BSName, BWorkPlace});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAsdderss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adderss1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(BWorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Adderss1, Email, Fname, NIC, Phone, Sname});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BAsdderss, BEmail, BFName, BPhone, BSName, BWorkPlace});

        Save.setText("Save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UBDetailsLayout = new javax.swing.GroupLayout(UBDetails);
        UBDetails.setLayout(UBDetailsLayout);
        UBDetailsLayout.setHorizontalGroup(
            UBDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UBDetailsLayout.createSequentialGroup()
                .addGroup(UBDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UBDetailsLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(Save))
                    .addGroup(UBDetailsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(profilePIC)
                        .addGap(87, 87, 87)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(182, 182, 182))
        );
        UBDetailsLayout.setVerticalGroup(
            UBDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UBDetailsLayout.createSequentialGroup()
                .addGroup(UBDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UBDetailsLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(UBDetailsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(profilePIC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Save)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UBDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UBDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        // TODO add your handling code here:
        String NICNO =BNIC.getText();
        String DFname = BFName.getText();
        String DLname = BSName.getText();
        String DAddress = BAsdderss.getText();
        String DEmail = BEmail.getText();
        String DPhoneNo = BPhone.getText();
        String DWorkPlace = BWorkPlace.getText();
        
        try {
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
        // executeUpdate(String SQL):
        String s = "update Customer set Fname=?, Lname=?, Address=?, Email=?, Phone=?, University_School_WorkPlace=? where NIC=?";
        PreparedStatement ps = con.prepareStatement(s);
        
        ps.setString(1, DFname);
        ps.setString(2, DLname);
        ps.setString(3, DAddress);
        ps.setString(4, DEmail);
        ps.setString(5, DPhoneNo);
        ps.setString(6, DWorkPlace);
        ps.setString(7, NICNO);
        ps.executeUpdate();
        //executeUpdate(String SQL)
        
        ////////Update deatails///////////////////////
       String ID =BNIC.getText();
        
        String st = "select * from customer where NIC=?";
        PreparedStatement pst = con.prepareStatement(st);
        pst.setString(1, ID);
        ResultSet rs = pst.executeQuery();
       
        if (rs.next()) {
            String Nic = rs.getString("NIC");
            String FName = rs.getString("Fname");
            String Lname = rs.getString("Lname");
            String Address = rs.getString("Address");
            String Email1 = rs.getString("Email");
            String PhoneNo = rs.getString("Phone");
            String WorkPlace = rs.getString("University_School_WorkPlace");
            
            
            BoaderDetails bodaerdetails = new BoaderDetails(Nic, FName, Lname, Address, Email1, PhoneNo, WorkPlace);
            UBDetails.removeAll();
            UBDetails.add(bodaerdetails).setVisible(true);
        }
        //////////Update deatails////////////////////
       
        pst.executeQuery();
        //The close() method is used to close the stream and release 
        //the resources that were busy in the stream
        ps.close();
        pst.close();
        con.close();
        
          
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
        
            System.out.println(e);
        
        }
        
        
    }//GEN-LAST:event_SaveMouseClicked

    private void BPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adderss1;
    private javax.swing.JTextField BAsdderss;
    private javax.swing.JTextField BEmail;
    private javax.swing.JTextField BFName;
    private javax.swing.JLabel BNIC;
    private javax.swing.JTextField BPhone;
    private javax.swing.JTextField BSName;
    private javax.swing.JTextField BWorkPlace;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel NIC;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Phone1;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Sname;
    private javax.swing.JPanel UBDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel profilePIC;
    // End of variables declaration//GEN-END:variables
}
