/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Home;

import Login.LoginHome;
import Register.Register_Home;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class Body_L_R extends javax.swing.JInternalFrame {

    /**
     * Creates new form Body
     */
    public Body_L_R() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HBody = new javax.swing.JPanel();
        LOGING = new javax.swing.JLabel();
        SINGUP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(766, 115));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        HBody.setBackground(new java.awt.Color(59, 119, 209));
        HBody.setPreferredSize(new java.awt.Dimension(1024, 440));

        LOGING.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        LOGING.setForeground(new java.awt.Color(255, 255, 255));
        LOGING.setText("LOGING");
        LOGING.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGING.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LOGINGMouseDragged(evt);
            }
        });
        LOGING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINGMouseClicked(evt);
            }
        });

        SINGUP.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SINGUP.setForeground(new java.awt.Color(255, 255, 255));
        SINGUP.setText("SINGUP");
        SINGUP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SINGUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SINGUPMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("BoardingHub is an online platform that simplifies the process offinding and managing boarding for anyone. It\nis a comprehensive solution that connects boarding house owners with people looking for boarding, and\nprovides a user-friendly interface for people to search, select, and manage boarding options according to theirBoardingHub \nis an online platform that simplifies the process offinding and managing boarding for anyone. It is a comprehensive solution \nthat connects boarding house owners with people looking for boarding, andprovides a user-friendly interface for people to\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout HBodyLayout = new javax.swing.GroupLayout(HBody);
        HBody.setLayout(HBodyLayout);
        HBodyLayout.setHorizontalGroup(
            HBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HBodyLayout.createSequentialGroup()
                .addGap(0, 170, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(HBodyLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(LOGING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(SINGUP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HBodyLayout.setVerticalGroup(
            HBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HBodyLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SINGUP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(HBody);
        HBody.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINGMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINGMouseDragged

    private void LOGINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINGMouseClicked
        // TODO add your handling code here:
        LoginHome login = new LoginHome();
        HBody.removeAll();
        HBody.add(login).setVisible(true);
    }//GEN-LAST:event_LOGINGMouseClicked

    private void SINGUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SINGUPMouseClicked
        // TODO add your handling code here:
        Register_Home reg = new Register_Home();
        HBody.removeAll();
        HBody.add(reg).setVisible(true);
    }//GEN-LAST:event_SINGUPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HBody;
    private javax.swing.JLabel LOGING;
    private javax.swing.JLabel SINGUP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
