/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Login;

import Boaders_Interface.B_Interface;
import Boaders_Interface.BoaderDetails;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Home.BH_Home;
import Home.B_Body;
import Home.Body;
import O_Interface.O_Interface;
import Register.Register_Home;
import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public LoginHome() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        LNIC = new javax.swing.JTextField();
        NIC = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        LPassword = new javax.swing.JPasswordField();
        LShowPassword = new javax.swing.JCheckBox();
        LReset = new javax.swing.JButton();
        LLogin = new javax.swing.JButton();
        LBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);

        login.setBackground(new java.awt.Color(29, 119, 209));
        login.setToolTipText("");
        login.setPreferredSize(new java.awt.Dimension(1024, 440));

        LNIC.setBackground(new java.awt.Color(29, 119, 209));
        LNIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LNIC.setForeground(new java.awt.Color(255, 255, 255));
        LNIC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        LNIC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        NIC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIC.setForeground(new java.awt.Color(255, 255, 255));
        NIC.setText("NIC");

        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");

        LPassword.setBackground(new java.awt.Color(29, 119, 209));
        LPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LPassword.setForeground(new java.awt.Color(255, 255, 255));
        LPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        LShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        LShowPassword.setText("Show Password");
        LShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LShowPasswordActionPerformed(evt);
            }
        });

        LReset.setText("RESET");
        LReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LResetActionPerformed(evt);
            }
        });

        LLogin.setText("LOGIN");
        LLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLoginActionPerformed(evt);
            }
        });

        LBack.setText("Back");
        LBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBackMouseClicked(evt);
            }
        });
        LBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/D_ICON/Untitled design (7).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Back !");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Don't have account yet? ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sing up");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(loginLayout.createSequentialGroup()
                                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(loginLayout.createSequentialGroup()
                                                .addComponent(LBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(LReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(53, 53, 53)
                                        .addComponent(LLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(loginLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(LNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(LPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LShowPassword)
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LShowPasswordActionPerformed
        // TODO add your handling code here:
        if (LShowPassword.isSelected()) {
            LPassword.setEchoChar((char) 0);
        } else {
            LPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_LShowPasswordActionPerformed

    private void LResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LResetActionPerformed
        // TODO add your handling code here:
        LNIC.setText("");
        LPassword.setText("");
    }//GEN-LAST:event_LResetActionPerformed

    private void LLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLoginActionPerformed

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            //select customer
            String s = "select * from customer where NIC=? and password=?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, LNIC.getText());
            ps.setString(2, LPassword.getText());
            ResultSet rs = ps.executeQuery();

            //////////////////////////////////////////////////////////////////////////////////
            /// select owners
            String st = "select * from owner where NIC=? and password=?";
            PreparedStatement pst = con.prepareStatement(st);
            pst.setString(1, LNIC.getText());
            pst.setString(2, LPassword.getText());
            ResultSet rst = pst.executeQuery();

            ////////////////////////////////////////////////////
            ///Select Admin
            String sa = "select * from admin where ID=? and Password=?";
            PreparedStatement psa = con.prepareStatement(sa);
            psa.setString(1, LNIC.getText());
            psa.setString(2, LPassword.getText());
            ResultSet rsa = psa.executeQuery();

            //cheak customer
            if (rs.next()) {
                String ID = rs.getString("NIC");
                //JOptionPane.showMessageDialog(this, "Boader Login Succesfully");

                //this.setVisible(false);
                /*B_Interface reg1 =new B_Interface();
                reg1.show();
                this.dispose();
                reg1.setVisible(true);*/
                String Nic = rs.getString("NIC");
                String FName = rs.getString("Fname");
                String Lname = rs.getString("Lname");
                String Address = rs.getString("Address");
                String Email = rs.getString("Email");
                String PhoneNo = rs.getString("Phone");
                String WorkPlace = rs.getString("University_School_WorkPlace");

                //BoaderDetails bodaerdetails = new BoaderDetails(Nic, FName, Lname, Address, Email, PhoneNo, WorkPlace);
                B_Interface body = new B_Interface(FName, Nic,Lname, Address, Email, PhoneNo, WorkPlace);
                login.removeAll();
                login.add(body).setVisible(true);

            } /// cheak owners
            else if (rst.next()) {
                String ID = rst.getString("NIC");
                String FName = rst.getString("Fname");
                String Lname = rst.getString("Lname");
                String Address = rst.getString("Email");
                String Email = rst.getString("Address");
                String PhoneNo = rst.getString("Phone");
                

                
                O_Interface body = new O_Interface(FName,ID, Lname, Address, Email, PhoneNo);
                login.removeAll();
                login.add(body).setVisible(true);

            } //cheak admin
            else if (rsa.next()) {
                //int ID =rsa.getInt("ID");
                JOptionPane.showMessageDialog(this, "ADDMIN Login Succesfully");
                this.setVisible(false);

                /* String username = rsa.getString("Name");
                new Home(username).setVisible(true);*/
            } else {
                JOptionPane.showMessageDialog(this, "Login Failed", "Message", JOptionPane.ERROR_MESSAGE);
                LNIC.setText("");
                LPassword.setText("");
            }
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {

            System.out.println(e);

        }
    }//GEN-LAST:event_LLoginActionPerformed

    private void LBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBackActionPerformed

    }//GEN-LAST:event_LBackActionPerformed

    private void LBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBackMouseClicked
        // TODO add your handling code here:
        B_Body body = new B_Body();
        login.removeAll();
        login.add(body).setVisible(true);


    }//GEN-LAST:event_LBackMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Register_Home reg = new Register_Home();
        login.removeAll();
        login.add(reg).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LBack;
    private javax.swing.JButton LLogin;
    private javax.swing.JTextField LNIC;
    private javax.swing.JPasswordField LPassword;
    private javax.swing.JButton LReset;
    private javax.swing.JCheckBox LShowPassword;
    private javax.swing.JLabel NIC;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel login;
    // End of variables declaration//GEN-END:variables
}
