/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Register;

import Home.BH_Home;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Owner extends javax.swing.JInternalFrame {

    /**
     * Creates new form Owner
     */
    public Owner() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RNIC = new javax.swing.JLabel();
        RFname = new javax.swing.JLabel();
        RSname = new javax.swing.JLabel();
        RAdderss = new javax.swing.JLabel();
        REmail = new javax.swing.JLabel();
        RPhone = new javax.swing.JLabel();
        URNIC = new javax.swing.JTextField();
        URFName = new javax.swing.JTextField();
        URSName = new javax.swing.JTextField();
        URAdderss = new javax.swing.JTextField();
        UREmail = new javax.swing.JTextField();
        URPhone = new javax.swing.JTextField();
        RNIC1 = new javax.swing.JLabel();
        RNIC2 = new javax.swing.JLabel();
        URPassword = new javax.swing.JPasswordField();
        URCPassword = new javax.swing.JPasswordField();
        URCheak = new javax.swing.JCheckBox();
        URClear = new javax.swing.JButton();
        URegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(876, 476));

        jPanel1.setBackground(new java.awt.Color(29, 119, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(864, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RNIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RNIC.setForeground(new java.awt.Color(255, 255, 255));
        RNIC.setText("NIC");
        jPanel1.add(RNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        RFname.setBackground(new java.awt.Color(54, 161, 212));
        RFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RFname.setForeground(new java.awt.Color(255, 255, 255));
        RFname.setText("Frist Name");
        jPanel1.add(RFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 130, 30));

        RSname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RSname.setForeground(new java.awt.Color(255, 255, 255));
        RSname.setText("Second Name ");
        jPanel1.add(RSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 130, 30));

        RAdderss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RAdderss.setForeground(new java.awt.Color(255, 255, 255));
        RAdderss.setText("Adderss");
        jPanel1.add(RAdderss, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 130, 30));

        REmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        REmail.setForeground(new java.awt.Color(255, 255, 255));
        REmail.setText("Email");
        jPanel1.add(REmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 30));

        RPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RPhone.setForeground(new java.awt.Color(255, 255, 255));
        RPhone.setText("Phone Number");
        jPanel1.add(RPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 30));

        URNIC.setBackground(new java.awt.Color(29, 119, 209));
        URNIC.setForeground(new java.awt.Color(255, 255, 255));
        URNIC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        URNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URNICActionPerformed(evt);
            }
        });
        jPanel1.add(URNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 220, 30));

        URFName.setBackground(new java.awt.Color(29, 119, 209));
        URFName.setForeground(new java.awt.Color(255, 255, 255));
        URFName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        URFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URFNameActionPerformed(evt);
            }
        });
        jPanel1.add(URFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 220, 30));

        URSName.setBackground(new java.awt.Color(29, 119, 209));
        URSName.setForeground(new java.awt.Color(255, 255, 255));
        URSName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        URSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URSNameActionPerformed(evt);
            }
        });
        jPanel1.add(URSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 30));

        URAdderss.setBackground(new java.awt.Color(29, 119, 209));
        URAdderss.setForeground(new java.awt.Color(255, 255, 255));
        URAdderss.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(URAdderss, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, 30));

        UREmail.setBackground(new java.awt.Color(29, 119, 209));
        UREmail.setForeground(new java.awt.Color(255, 255, 255));
        UREmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(UREmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, 30));

        URPhone.setBackground(new java.awt.Color(29, 119, 209));
        URPhone.setForeground(new java.awt.Color(255, 255, 255));
        URPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(URPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, 30));

        RNIC1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RNIC1.setForeground(new java.awt.Color(255, 255, 255));
        RNIC1.setText("Password");
        jPanel1.add(RNIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, 30));

        RNIC2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RNIC2.setForeground(new java.awt.Color(255, 255, 255));
        RNIC2.setText("Confirm Password");
        jPanel1.add(RNIC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, 30));

        URPassword.setBackground(new java.awt.Color(29, 119, 209));
        URPassword.setForeground(new java.awt.Color(255, 255, 255));
        URPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(URPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 220, 25));

        URCPassword.setBackground(new java.awt.Color(29, 119, 209));
        URCPassword.setForeground(new java.awt.Color(255, 255, 255));
        URCPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(URCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 220, 25));

        URCheak.setForeground(new java.awt.Color(255, 255, 255));
        URCheak.setText("I accept the terms of use & privacy policy");
        URCheak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URCheakActionPerformed(evt);
            }
        });
        jPanel1.add(URCheak, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 266, -1));

        URClear.setText("Clear");
        URClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URClearActionPerformed(evt);
            }
        });
        jPanel1.add(URClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 120, 30));

        URegister.setText("Register");
        URegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URegisterActionPerformed(evt);
            }
        });
        jPanel1.add(URegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 120, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void URNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URNICActionPerformed

    private void URFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URFNameActionPerformed

    private void URSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URSNameActionPerformed

    private void URCheakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URCheakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URCheakActionPerformed

    private void URClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URClearActionPerformed
        // TODO add your handling code here:
        URNIC.setText("");
        URFName.setText("");
        URSName.setText("");
        URAdderss.setText("");
        UREmail.setText("");
        URPhone.setText("");
        URPassword.setText("");
        URCPassword.setText("");
    }//GEN-LAST:event_URClearActionPerformed

    private void URegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URegisterActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            String s = "Insert into owner values (?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, URNIC.getText());
            String inputText = URNIC.getText();
//            /////NIC Validation////
                if(URNIC.getText().length()==10){
                if(inputText.endsWith("v")){
                }
                else{
                    JOptionPane.showMessageDialog(this, "Invalid NIC Number");
                    URNIC.setText("");
                    return;
                }
                }
                if(URNIC.getText().length()!=10 && URNIC.getText().length()!=12){
                    JOptionPane.showMessageDialog(this, "Invalid NIC Number");
                    URNIC.setText("");
                    return;
                }
            ps.setString(2, URFName.getText());
            ps.setString(3, URSName.getText());
            ps.setString(4, UREmail.getText());
            ps.setString(5, URAdderss.getText());
            ps.setString(6, URPhone.getText());
            /////Phone Validation////
//            if(URPhone.getText().length()!=10){
//                JOptionPane.showMessageDialog(this, "Invalid Phone Number");
//                URPhone.setText("");
//                return;
//            }
            ps.setString(7, URPassword.getText());
           

            if(!(new String(URPassword.getPassword()).endsWith(new String(URCPassword.getPassword()))))
            {
                JOptionPane.showMessageDialog(this, "Youre password Does not Match","Message",JOptionPane.ERROR_MESSAGE);
                URPassword.setText("");
                URCPassword.setText("");
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Register Successfully");

               // ps.executeUpdate();
               

                /*JOptionPane.showMessageDialog(URegister ,rs + rst); */

                URNIC.setText("");
                URFName.setText("");
                URSName.setText("");
                URAdderss.setText("");
                UREmail.setText("");
                URPhone.setText("");
                URPassword.setText("");
                URCPassword.setText("");
                //The close() method is used to close the stream and release
                //the resources that were busy in the stream
                ps.executeUpdate();
                ps.close();
                con.close();

                BH_Home reg1 =new BH_Home();
                reg1.show();
                this.dispose();
                reg1.setVisible(true);

            }
        }

        catch(HeadlessException | ClassNotFoundException | SQLException e){

            System.out.println(e);

        }
    }//GEN-LAST:event_URegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RAdderss;
    private javax.swing.JLabel REmail;
    private javax.swing.JLabel RFname;
    private javax.swing.JLabel RNIC;
    private javax.swing.JLabel RNIC1;
    private javax.swing.JLabel RNIC2;
    private javax.swing.JLabel RPhone;
    private javax.swing.JLabel RSname;
    private javax.swing.JTextField URAdderss;
    private javax.swing.JPasswordField URCPassword;
    private javax.swing.JCheckBox URCheak;
    private javax.swing.JButton URClear;
    private javax.swing.JTextField UREmail;
    private javax.swing.JTextField URFName;
    private javax.swing.JTextField URNIC;
    private javax.swing.JPasswordField URPassword;
    private javax.swing.JTextField URPhone;
    private javax.swing.JTextField URSName;
    private javax.swing.JButton URegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    byte[] photo =null;
    String filename =null; 
}
