/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Register;

import Home.BH_Home;
import Home.B_Body;
import Home.Body;
import Login.LoginHome;
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class Register_Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register_Home
     */
    Color DefaultColor,ClickedColor;
    
    public Register_Home() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
       
        //set Default color to pan on run time
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RE_Body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LBack = new javax.swing.JButton();
        Boader = new javax.swing.JLabel();
        Owner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RE_Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1024, 464));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RE_Body.setPreferredSize(new java.awt.Dimension(1024, 440));

        jPanel1.setBackground(new java.awt.Color(59, 119, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBack.setText("Back");
        LBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBackMouseClicked(evt);
            }
        });
        LBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBackActionPerformed(evt);
            }
        });
        jPanel1.add(LBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 30));

        Boader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Boader.setText("      Boaders");
        Boader.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoaderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoaderMousePressed(evt);
            }
        });
        jPanel1.add(Boader, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 210, 110, -1));

        Owner.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Owner.setText("     Owner");
        Owner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OwnerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OwnerMousePressed(evt);
            }
        });
        jPanel1.add(Owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/D_ICON/left bar7.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 440));

        RE_Home.setBackground(new java.awt.Color(29, 119, 209));
        RE_Home.setPreferredSize(new java.awt.Dimension(864, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/D_ICON/11.png"))); // NOI18N

        javax.swing.GroupLayout RE_HomeLayout = new javax.swing.GroupLayout(RE_Home);
        RE_Home.setLayout(RE_HomeLayout);
        RE_HomeLayout.setHorizontalGroup(
            RE_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RE_HomeLayout.setVerticalGroup(
            RE_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RE_BodyLayout = new javax.swing.GroupLayout(RE_Body);
        RE_Body.setLayout(RE_BodyLayout);
        RE_BodyLayout.setHorizontalGroup(
            RE_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RE_BodyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RE_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RE_BodyLayout.setVerticalGroup(
            RE_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(RE_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(RE_Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerMouseClicked
        // TODO add your handling code here:
        Owner owner = new Owner();
        RE_Home.removeAll();
        RE_Home.add(owner).setVisible(true);
    }//GEN-LAST:event_OwnerMouseClicked

    private void BoaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoaderMouseClicked
        // TODO add your handling code here:
        Boaders boaders = new Boaders();
        RE_Home.removeAll();
        RE_Home.add(boaders).setVisible(true);
    }//GEN-LAST:event_BoaderMouseClicked

    private void LBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBackMouseClicked
        // TODO add your handling code here:
        B_Body body = new B_Body();
        RE_Body.removeAll();
        RE_Body.add(body).setVisible(true);
    }//GEN-LAST:event_LBackMouseClicked

    private void OwnerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OwnerMousePressed

    private void BoaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoaderMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BoaderMousePressed

    private void LBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBackActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boader;
    private javax.swing.JButton LBack;
    private javax.swing.JLabel Owner;
    private javax.swing.JPanel RE_Body;
    private javax.swing.JPanel RE_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
